"""create lanmsgs and assignments tables

迁移 ID: 6b93b8111e66
父迁移: d2b8208195c1
创建时间: 2024-09-29 17:41:00.769275

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6b93b8111e66'
down_revision: str | Sequence[str] | None = 'd2b8208195c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
