"""create lanmsgs and assignments tables

迁移 ID: d2b8208195c1
父迁移: 
创建时间: 2024-09-29 17:33:32.176449

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd2b8208195c1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lanmsgs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sheet_id', sa.String(length=255), nullable=False),
    sa.Column('sheet_no', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lanmsgs')),
    sa.UniqueConstraint('sheet_id'),
    info={'bind_key': 'lanunion'}
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lanmsg_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('assign_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lanmsg_id'], ['lanmsgs.id'], name=op.f('fk_assignments_lanmsg_id_lanmsgs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments')),
    info={'bind_key': 'lanunion'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    op.drop_table('lanmsgs')
    # ### end Alembic commands ###
